Updated flake - Disbled lang formater in `nvf.nix`
It fials to build with error:

```text
   error: attribute 'prettier' missing
       at /nix/store/3vzc8fxjxvv0b0jrywian6ilb7bdk4y8-source/modules/plugins/languages/css.nix:45:17:
           44|     prettier = {
           45|       package = pkgs.prettier;
             |                 ^
          46|     };
```

 On branch main
 Your branch is up to date with 'origin/main'.

 Changes to be committed:
	modified:   CHANGELOG.md
	modified:   flake.lock
	modified:   modules/home/nvf.nix